name: CI-Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Gradle cache
      - name: Cache Gradle package
        uses: actions/cache@v4
        with: 
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Set up Dependencies
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --parallel

      # Run all JUnit test classes
      - name: Run tests
        run: ./gradlew test --no-daemon

